spring:
  config:
    import: "optional:sm://"
  data:
    mongodb:
      uri: mongodb+srv://${USER_DB}:${sm://PASSWORD_DB/1}@lottery-validation-clus.cb6sj7y.mongodb.net/?authSource=admin&appName=lottery-validation-cluster
      database: lottery_statistics_db
  cloud:
    gcp:
      core:
        enabled: true
      parametermanager:
        enabled: false
      secretmanager:
        enabled: true
        project-id: lottery-validation-service
