spring:
  application:
    name: lottery-validation-service
  
  profiles:
    active: ${SPRING_PROFILE:dev}
  
  # No Spring Boot 4 nao tem mais o prefix spring.data.mongodb, comeca ser spring.mongodb
  mongodb:
    uri: ${MONGODB_URI:mongodb://lotteryuser:lotterypass@localhost:27017/lottery_statistics_db?authSource=admin}
    database: lottery_statistics_db
    representation:
      uuid: STANDARD

# No Jackson 3, o comportamento padrão já é ISO-8601, ou seja: "2025-12-17T00:10:30"  
  # jackson:
  #   serialization:
  #     write-dates-as-timestamps: false
  #   time-zone: UTC

server:
  port: ${SERVER_PORT:8080}
  servlet:
    # context-path: /lottery-validation
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    com.lottery.validation: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
