spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER_DB:lotteryuser}:${MONGO_PASS_DB:lotterypass}@${MONGO_ADDRESS_DB:localhost}:${MONGO_PORT:27017}/${DATABASE_NAME:lottery_statistics_db}?authSource=${MONGO_AUTH_DB:admin}
  cloud:
    gcp:
      parametermanager:
        enabled: false
      core:
        enabled: false
      secretmanager:
        enabled: false