spring:
  application:
    name: lottery-validation-service
  data:
    mongodb:
      uuid-representation: STANDARD

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

evolution:
  api:
    url: ${EVOLUTION_API_URL}
    key: ${EVOLUTION_API_KEY}

caixa:
  api:
    url: ${CAIXA_API_URL}